#!/bin/csh -f

echo "clean up old files"
rm -rf results_vcsAms_3step csrc simv_3step.msv simv3_step.daidir AN.DB

echo "mkdir ./results_vcsAms_3step"
mkdir ./results_vcsAms_3step

# Analyze
echo "verilog analysis - vlogan"
vlogan \
	-full64 \
	testbench.v \
	adder.v	\
	-l ./results_vcsAms_3step/vlogan.log

# Elaborate
echo "design elaboration - vcs"
vcs \
	-full64 \
	top \
	-debug_access+all \
	-ad=vcsAD_3step.init \
	-l ./results_vcsAms_3step/vcs.log \
	-o simv_3step
	
# Simulate
echo "run simulation - simv"
simv_3step \
	+COMPARE \
	-l ./results_vcsAms_3step/simv3_step.log
	
mv ./vcs.fsdb ./results_vcsAms_3step/
