#!/bin/csh -f

echo "clean up old files"
rm -rf results_vcs simvVcs.daidir csrc

echo "mkdir ./results_vcs"
mkdir ./results_vcs

# Compile
echo "verilog compilation"
vcs \
	-full64 \
	testbench.v \
	adder.v	\
	-debug_access+all \
	-l ./results_vcs/vcs.log \
	-o simvVcs
	
# Simulate
echo "run simulation - simvVcs"
simvVcs \
	+COMPARE \
	-l ./results_vcs/simvVcs.log

mv ./vcs.fsdb ./results_vcs/
